### PR TITLE
Updating gemspec template to eliminate gem build deprecation warnings.

### PR DESCRIPTION
**Pull request by onewheelskyward**

### CODE REVIEW

**Comment by jimmycuadra** [comment]
What deprecation warnings are you seeing?

**Comment by onewheelskyward** [comment]
My apologies, they aren't deprecation warnings, just warnings about not using semver for dependencies.

Here's the full dump from a lita handler generated gemspec (after removing the TODO:s):

```
~/lita-test> gem build lita-test.gemspec
fatal: Not a git repository (or any of the parent directories): .git
WARNING:  open-ended dependency on lita (>= 4.4) is not recommended
  if lita is semantically versioned, use:
    add_runtime_dependency 'lita', '~> 4.4'
WARNING:  open-ended dependency on pry-byebug (>= 0, development) is not recommended
  if pry-byebug is semantically versioned, use:
    add_development_dependency 'pry-byebug', '~> 0'
WARNING:  open-ended dependency on rake (>= 0, development) is not recommended
  if rake is semantically versioned, use:
    add_development_dependency 'rake', '~> 0'
WARNING:  open-ended dependency on rack-test (>= 0, development) is not recommended
  if rack-test is semantically versioned, use:
    add_development_dependency 'rack-test', '~> 0'
WARNING:  open-ended dependency on rspec (>= 3.0.0, development) is not recommended
  if rspec is semantically versioned, use:
    add_development_dependency 'rspec', '~> 3.0', '>= 3.0.0'
WARNING:  open-ended dependency on simplecov (>= 0, development) is not recommended
  if simplecov is semantically versioned, use:
    add_development_dependency 'simplecov', '~> 0'
WARNING:  open-ended dependency on coveralls (>= 0, development) is not recommended
  if coveralls is semantically versioned, use:
    add_development_dependency 'coveralls', '~> 0'
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: lita-test
  Version: 0.1.0
  File: lita-test-0.1.0.gem
```

**Comment by onewheelskyward** [comment]
It's something I end up fixing every time I generate a handler, so I figured a template update was appropriate.

**Comment by jimmycuadra** [comment]
Hmm. I'm gonna need to look into this, because I specifically *don't* want to lock versions down like that. I'm surprised RubyGems would attempt to enforce something in such a gray area. (Well, maybe I'm not surprised. :disappointed:)

**Comment by onewheelskyward** [comment]
I hear you on that.  The nice thing about following semver is that as long as you stay up to date with minor revisions, it won't break your app.  The problem with open-ended dependencies is that a major change can and likely will break something without changes on your end, too.

**Comment by jimmycuadra** [comment]
A lot of the time major version upgrades don't break anything, though. In SemVer the major version change just means there was *any* backwards incompatible change, not that any code using the library will automatically break. This issue actually created a problem in Lita, because the original plugin templates locked them to Lita's 2.x.x series. When Lita 3 came out, all those plugins had to be manually updated to keep working, even though 3 was almost completely backwards compatible with 2. That was difficult because there were quite a number of plugins by that point, and some of them did not have very responsive authors.

**Comment by jimmycuadra** [comment]
It seems this behavior has been in RubyGems for quite some time. I don't get why it's never shown up for Lita before. In any case, Lita's use of open-ended dependencies is intentional and not something I want to change. If there is a way to opt-out/disable this particular warning, that would be an acceptable change, but otherwise we may have to live with RubyGems's annoying behavior in this case.

**Pull request closed without merging**
