### PR TITLE
allow user to send message from a room in tests

### PR DESCRIPTION
**Pull request by nickjer**
Allows developers to write specs that have users sending messages directly to the bot or from a room. Makes it easier to test private and public messages.

### CODE REVIEW

**Comment by jimmycuadra** [comment]
Good addition! Let's make it accept a `Lita::Room` object instead of a string. Rooms as strings will slowly be phased out now that there's a real room object, so any new APIs should use them.

**Comment by nickjer** [comment]
Thanks. I have been using it extensively to check whether a message was public or private in a game I am building.

Also, I am not quite sure what you mean by "make it accept `Lita::Room`". There is really nothing stopping it from accepting it. In fact I already send it `Lita::Room`

Here is a snippet from one of my personal specs

```
let (:room) { Lita::Room.create_or_update(555, name: "Room") }
...
before(:example) do
  send_message(".play", from: room)
end
```

Let me know if you need me to change something.

**Comment by jimmycuadra** [comment]
Yes, you're right. I guess all I'd change is the YARD doc for that parameter – I'd like the argument type to be `Lita::Room` instead of `String` (even though string will technically work) to encourage people to use room objects.

I'd also like to have a test case for this both for documentation of expected behavior and to prevent regressions. Thank you for your work on this!

**Comment by nickjer** [comment]
Hah, sorry, I am an idiot. I completely glossed over that YARD doc parameter.

I also added some basic tests. Let me know if those are enough, or if I should test even more.

**Comment by jimmycuadra** [comment]
Thank you!

**Pull request merged**
