### PR TITLE
Update gemspec.tt

### PR DESCRIPTION
**Pull request by jjasghar**
Everyone needs pry :metal:

### CODE REVIEW

**Comment by jimmycuadra** [comment]
I'd say this is a reasonable default to have. Let's make it even more useful and include pry-byebug instead!

**Comment by jjasghar** [comment]
Touche' I'll update the PR ASAP.

**Comment by jimmycuadra** [comment]
Thank you very much!

**Comment by jjasghar** [comment]
I finally wrapped my head around lita and saw the light. I still love my hubot but lita is quickly over passing em.

**Pull request merged**
