### PR TITLE
making the shell adapter source have a room called 'shell_room'

### PR DESCRIPTION
**Pull request by natesholland**
I would like to have it so that when you are running in shell it looks like the source of a response is coming from a chat room. This is in line with how hubut works as well when running in shell.

### CODE REVIEW

**Comment by jimmycuadra** [comment]
Good idea! There's a configuration option for the shell adapter, `:private_chat`, which lets you control whether the shell-based chat is simulating a private chat or a group chat that happens to only have you and the bot in it. Currently the only thing it affects is whether or not the bot will respond to commands without the message being prefixed with its name.

I think it would make sense to extend the semantics of the configuration attribute to include the "shell" room name when it's in the regular mode, and not include it when it's in private chat mode. This would more closely mimic how it behaves in other environments.

Of course, some tests for these details will be necessary as well. If you're up to doing it yourself, that'd be great. If not, no worries, and I will leave this open as a reminder to implement this functionality soon.

Thanks for the PR!

**Comment by natesholland** [comment]
Ok I have made it so that when `:private_chat` is set to false the room is `'shell_room'` and then if it is set to true the room is `nil`.

I have also added tests: `"sets the room to 'shell_room' if config.adapters.shell.private_chat is false"` and `"sets the room to nil if config.adapters.shell.private_chat is true"`

This should be ready to merge in unless you want me to rebase the two commits into one or have any other tweaks you would like to do.

**Comment by jimmycuadra** [comment]
Looks great! Thanks for the contribution!

**Comment by natesholland** [comment]
Sweet, thanks for pulling it in. How long until this makes it onto rubygems?

**Comment by jimmycuadra** [comment]
Release in [4.3.2](https://github.com/jimmycuadra/lita/releases/tag/v4.3.2). (I also renamed "shell_room" to just "shell" for simplicity.)

**Pull request merged**
